services:
  db:
    image: postgres:15
    container_name: testshop-db-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: testshop-app-1
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/appdb?sslmode=disable"
      JWT_SECRET: "JWT"
      ADMIN_LOGIN: "archibald"
      ADMIN_PASSWORD: "archibaldpass"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
